# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  validate_sites:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: |
            composer install
            ./bin/validateSites.php
# Orchestrate or schedule a set of jobs
workflows:
  commit:
    jobs:
      - validate_sites
